### ISSUE TITLE
Alyssa has a windows computer

### ISSUE THREAD

**Issue by alyssa-blair** [wrighted/FirstTracks#2]
No mac, no swift :(

**Comment by wrighted** [comment]
Has this been resolved?

If not, please checkout [this](https://www.apple.com/ca/shop/buy-mac/macbook-pro).

**Comment by alyssa-blair** [comment]
ah yes thank you ethan. was even more useful the second time you sent it.

**Comment by alyssa-blair** [comment]
Issue has been resolved, successfully robbed jared.

**Comment by wrighted** [comment]
There are some ambiguities in your solution. Will need to open a ticket to clarify.
