### ISSUE TITLE
what do

### ISSUE THREAD

**Issue by jaredwebber** [wrighted/FirstTracks#4]
*what do?*

**Comment by wrighted** [comment]
Take a look at the `README`.

**Comment by wrighted** [comment]
Also `GoogleSignIn` doesn't work, something wrong with the `GIDClientID`.

Can pass `Firebase` credential offline if interested.

**Comment by jaredwebber** [comment]
> Also `GoogleSignIn` doesn't work, something wrong with the `GIDClientID`.
> 
> Can pass `Firebase` credential offline if interested.

Did you create a new app inside firebase (and replace the relevant files in Xcode)? And if so what firebase account is it under

**Comment by jaredwebber** [comment]
app done ✅
